# config/services.yaml

parameters:
    image_dir: '%kernel.project_dir%/public/uploads/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    # Add more service definitions here if needed
